name: Install Go dependencies
run-name: Install Go dependencies
on: [push]
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.16.x'
      
      - name: Install dependencies
        run: |
          go get .

      - name: Run
        run: go run -v ./hello-world.go